blank_issues_enabled: false
contact_links:
  - name: 💬 Suporte ou dúvidas gerais
    url: https://github.com/MKCodec/Mwsm/discussions
    about: Use a aba "Discussions" para dúvidas, sugestões ou feedback.
